// reference our namespace
var TodoApp = window.TodoApp || {};

;(function($){
	'use strict';
	// reference to todo list
	var $todo_list = $('#todo-list');
	var $title = $('#title');
	var $notes = $('#notes');
	var $important  = $('#important');
	var $todo_form = $('#todo-form');
	var $due = $('#due');

	//variable to hold model seed data
	var todo_data;

	//variable to hold an instance ofour ToDoModel
	var todo;

	//variable to hold new makup generated by 
	var todo_html;

	var todo_view;

	//add event handler to the button 
	$('#create-todo').on('click', function(e){
		//stop the form from submitting
		e.preventDefault();
		// build our todo _data object literal
		//using values from the form
		todo_data = {
			title: $title.val(),
			notes: $notes.val(),
			important: $important.is(':checked'),
			due: $due.val()
		};
		//create an instance of TodoModel
		todo = new TodoApp.TodoModel(todo_data);
		todo_view = new TodoApp.TodoView({ model: todo });

		// get hte html out of our view
		todo_html = todo_view.render().el;
		console.log(todo_html);

		// append the html to the list
		$todo_list.append(todo_html);

		$todo_form[0].reset();
	});	

})(window.jQuery);